import type { DrawingToolType } from "./interfaces/DrawingToolType.interface";

/** Plain-language "how this works" text for each drawing tool's own info icon (see ToolsRail.tsx)
 *  — same role `INDICATOR_DESCRIPTIONS` already plays for indicators, just for the tool-picker
 *  menus instead. "zoomIn" has no entry — it never reaches a menu at all (see
 *  DRAWING_DIAGRAMS' own doc for why), so nothing here ever needs to explain it to anyone.
 *
 *  Same formatting contract as `INDICATOR_DESCRIPTIONS`: real `\n` breaks inside each string —
 *  `\n\n` between topic chunks, `\n- ` before each item of a list — rendered by
 *  `.lq-chart__indicator-info-text`'s `white-space: pre-line` (see charts-shared.css). */
export const DRAWING_TOOL_DESCRIPTIONS: Partial<Record<DrawingToolType, string>> = {
  trendline:
    "Deux clics suffisent : le premier fixe le point de départ, le second l'extrémité, et le segment s'arrête exactement sur ces deux points. C'est l'outil de base de l'analyse graphique, celui qui matérialise une ligne de support en reliant des creux successifs, une résistance en reliant des sommets, ou l'axe d'une tendance.\n\nLa règle usuelle est qu'il faut au moins deux points de contact pour tracer la ligne et un troisième pour la valider — deux points suffisent toujours à faire une droite, c'est le troisième qui prouve que le marché la respecte. Ce qu'on surveille ensuite, c'est la cassure (une clôture franche de l'autre côté) et le retest, quand le prix revient toucher la ligne par en dessous après l'avoir franchie.\n\nLes deux extrémités restent librement déplaçables après coup, et la fenêtre d'édition permet ensuite de prolonger la ligne d'un côté ou des deux, ou de lui ajouter une pointe de flèche, sans avoir à la retracer. L'aimant, s'il est actif, accroche chaque nouveau point au prix d'ouverture, de plus haut, de plus bas ou de clôture le plus proche, ce qui évite les tracés approximatifs.",
  extended:
    "Une ligne de tendance classique, placée elle aussi en deux clics, mais prolongée au-delà de ses deux points d'ancrage jusqu'aux bords gauche et droit de la zone de prix. Les deux points cliqués continuent de définir la pente et restent les seules poignées déplaçables ; seul l'affichage change, la droite se contentant de poursuivre son chemin.\n\nL'intérêt est de projeter dans le futur une droite construite sur le passé : une oblique de support tracée sur trois creux anciens indique alors à quel prix elle passera dans deux semaines, ce qui donne un niveau à surveiller à l'avance plutôt qu'une observation a posteriori. Le prolongement vers la gauche sert de son côté à vérifier que la droite avait déjà un sens avant la zone qui a servi à la tracer.\n\nLa direction du prolongement — à gauche, à droite ou des deux côtés — se modifie ensuite dans la fenêtre d'édition, et n'importe quelle ligne de tendance ordinaire peut y être convertie de la même manière.",
  channel:
    "Le canal se place en trois clics. Les deux premiers tracent la ligne principale exactement comme une ligne de tendance ; le troisième fixe l'écart de la seconde ligne, mesuré comme la distance verticale en prix entre le point cliqué et la ligne principale à cette même date. Cet écart est ensuite appliqué tel quel sur toute la longueur, si bien que la seconde ligne est rigoureusement parallèle à la première — c'est une distance en prix et non une distance perpendiculaire, la simplification qu'utilisent la plupart des plateformes.\n\nOn l'emploie pour encadrer une tendance qui progresse en oscillant : la ligne basse regroupe les creux, la ligne haute les sommets, et l'espace entre les deux devient une zone de travail où l'on achète près du bas et où l'on allège près du haut tant que le canal tient.\n\nLes deux événements à surveiller sont la sortie par le haut, qui traduit une accélération, et la sortie par le bas, qui invalide la structure. Un canal correctement tracé demande idéalement deux points de contact sur chaque bord.",
  disjointChannel:
    "Le canal disjoint se place lui aussi en trois clics : les deux premiers définissent la première ligne, le troisième un écart de prix — mais au lieu de décaler une copie parallèle, cet écart sert à construire une seconde ligne dont la pente est inversée par rapport à la première. Concrètement, son extrémité éloignée est placée à l'écart demandé tandis que son extrémité proche est reflétée de l'autre côté, ce qui produit deux lignes qui convergent ou divergent au lieu de rester parallèles.\n\nLe résultat est donc bien un tracé à quatre points, mais le quatrième est calculé et non cliqué. Les deux points ainsi obtenus deviennent ensuite des poignées ordinaires, librement déplaçables, ce qui permet de rectifier l'angle à la main jusqu'à faire épouser aux deux bords la structure réelle.\n\nC'est l'outil des figures en biseau et en élargissement — triangle, coin ascendant ou descendant, mégaphone — que le canal parallèle classique est incapable de représenter.",
  horizontal:
    "Un seul clic pose un niveau de prix horizontal traversant toute la largeur du graphique, passé comme futur. C'est le tracé le plus simple et souvent le plus utile : anciens sommets et anciens creux, seuils psychologiques ronds, prix d'entrée d'une position, niveau de stop.\n\nContrairement à une oblique, un niveau horizontal ne dépend d'aucun choix de pente, donc de bien moins d'interprétation, ce qui le rend plus consensuel entre intervenants — et donc plus susceptible d'être réellement respecté. On observe surtout le nombre de fois où le prix y a réagi, et le fait qu'un ancien support se comporte souvent en résistance une fois cassé, et réciproquement.\n\nLa ligne se déplace ensuite verticalement à la souris. Détail utile : le niveau est posé dans le panneau où le clic a eu lieu — il peut donc tout aussi bien marquer un seuil dans le panneau des volumes ou dans celui d'un oscillateur comme le RSI, et non seulement sur les prix.",
  ray: "Identique à la ligne horizontale sur le fond — un seul clic, un seul niveau de prix — à ceci près qu'elle ne couvre pas tout l'historique : elle démarre à la date cliquée et se poursuit uniquement vers la droite, jusqu'au bord du graphique.\n\nC'est exactement ce qu'il faut lorsque le niveau n'a de sens qu'à partir d'un événement précis : le sommet d'où part une résistance, le point de cassure d'une figure, le prix d'entrée d'une position, l'annonce à partir de laquelle un plancher s'est installé. Faire courir la ligne sur toute la période antérieure suggérerait à tort que le niveau existait déjà, et encombre la lecture.\n\nContrairement à la ligne horizontale, elle se déplace dans les deux dimensions : on peut ajuster son prix comme sa date de départ. Elle peut également être posée dans le panneau des volumes ou dans celui d'un oscillateur, selon l'endroit où le clic a été fait.",
  vertical:
    "Un seul clic pose un trait vertical sur toute la hauteur du graphique, à une date précise. Il ne dit rien des prix : il sert exclusivement de repère temporel, pour marquer une publication de résultats, une annonce de banque centrale, une décision d'entreprise, le début d'une session, ou simplement la date à laquelle on a pris une décision et que l'on souhaite retrouver plus tard.\n\nSon intérêt principal est la mise en relation : en alignant visuellement l'événement avec ce qui s'est produit sur les prix, les volumes et les indicateurs situés dessous, il permet de vérifier si une réaction a effectivement eu lieu et combien de temps elle a mis à se dissiper.\n\nUne fois posé, le trait ne se déplace qu'horizontalement, sa date changeant mais jamais son étendue verticale. Une étiquette de texte peut lui être ajoutée depuis la fenêtre d'édition pour nommer l'événement concerné.",
  pitchfork:
    "La fourche d'Andrews se construit sur trois clics — A, B et C — placés typiquement sur trois pivots successifs : un creux majeur, puis le sommet qui suit, puis le creux suivant. La médiane, tracée en pointillés, part de A et passe par le milieu du segment B-C ; deux lignes parallèles à cette médiane, les dents, passent respectivement par B et par C. Les segments A-B et B-C restent visibles pour montrer la construction.\n\nL'idée sous-jacente est que le prix, après une correction, a tendance à revenir vers la médiane, et que l'ensemble du mouvement s'inscrit dans le couloir dessiné par les deux dents. La lecture pratique en découle : tant que le prix évolue dans la fourche, la structure est valide, la médiane sert d'aimant et de ligne d'équilibre, et les deux dents servent de zones de retournement ; une sortie durable de la fourche, en particulier au-delà de la dent inférieure en tendance haussière, signale la fin de la structure.\n\nLa qualité du tracé dépend entièrement du choix des trois pivots : trois points mal choisis produisent une fourche qui ne décrit rien. Chacune des trois lignes parallèles peut être masquée individuellement depuis la fenêtre d'édition.",
  schiffPitchfork:
    "Variante de la fourche d'Andrews qui ne change qu'une chose, mais une chose déterminante : le point de départ de la médiane. Au lieu de partir de A, elle démarre à mi-chemin en prix entre A et B, tout en conservant la date de A — le déplacement se fait donc verticalement seulement. Les deux dents restent ancrées sur B et C et restent parallèles à cette médiane.\n\nLa raison d'être de cette modification est pratique : lorsque le segment A-B est très vertical, c'est-à-dire quand le premier mouvement a été brutal, la fourche classique produit un couloir trop incliné qui décroche rapidement du prix. En relevant l'origine de la médiane, la variante Schiff aplatit la fourche et la maintient collée à la structure réelle.\n\nLa lecture ne change pas par rapport à la fourche classique : retour vers la médiane, couloir borné par les dents, sortie durable comme signal d'invalidation. En pratique, on trace souvent les deux et on conserve celle qui épouse le mieux les réactions passées du prix.",
  modifiedSchiffPitchfork:
    "Seconde variante de la fourche, qui pousse la logique du Schiff un cran plus loin : la médiane part cette fois du milieu exact du segment A-B, c'est-à-dire décalé de moitié à la fois en prix et en date, là où le Schiff classique ne décale qu'en prix. Elle vise toujours le milieu du segment B-C, et les deux dents restent ancrées sur B et C, parallèles à cette médiane.\n\nLe décalage en date a un effet concret : il fait pivoter légèrement toute la fourche et l'aplatit davantage encore que le Schiff, ce qui la rend adaptée aux cas où le mouvement initial A-B a été à la fois violent et rapide.\n\nElle se lit exactement comme les autres fourches — médiane comme ligne d'équilibre, dents comme bornes du couloir, sortie durable comme invalidation. Le choix entre les trois variantes est empirique : on retient celle dont le couloir contient le mieux les oscillations déjà observées, puisque c'est ce qui donne le plus de crédit à sa projection à droite.",
  insidePitchfork:
    "Variante à la géométrie réellement différente des autres, et non à simple décalage d'origine. Elle se place toujours sur trois clics A, B et C, mais ses deux dents ne passent plus par B et C : elles passent par le milieu du segment A-B d'un côté et par B de l'autre. La médiane, elle, vient se placer exactement entre ces deux dents, ancrée au milieu du segment B-C.\n\nIl en résulte une fourche plus étroite et située à l'intérieur du couloir qu'aurait dessiné la fourche classique sur les mêmes points, d'où son nom. On y recourt lorsque le prix évolue dans un canal serré au sein d'un mouvement plus vaste, et que la fourche standard produit un couloir trop large pour être exploitable — l'Inside Pitchfork suit alors la structure fine plutôt que l'enveloppe générale.\n\nLa lecture reste la même : la médiane fait office de ligne d'équilibre, les deux dents bornent le mouvement, une sortie franche invalide la construction. Chaque ligne peut être masquée séparément dans la fenêtre d'édition.",
  rectangle:
    "Deux clics posent les deux coins opposés d'un rectangle, dessiné avec un contour et un remplissage léger de sa propre couleur. Il ne calcule rien : c'est un outil de délimitation, qui répond au besoin de dire « voilà la zone qui compte ».\n\nSes usages les plus fréquents :\n\n- le marquage d'un range de consolidation, dont les bords supérieur et inférieur deviennent des niveaux à surveiller ;\n- la matérialisation d'une zone de prix plutôt que d'un niveau unique, ce qui est souvent plus honnête qu'une ligne au pixel près puisqu'un support est en pratique une zone ;\n- la mise en évidence d'une période précise, par exemple les quelques séances entourant une publication.\n\nUn rectangle tracé sur une consolidation passée sert aussi de gabarit : on le duplique pour comparer l'amplitude et la durée d'une consolidation en cours à celles d'un épisode antérieur. Les deux coins restent déplaçables individuellement, et l'ensemble se déplace d'un bloc.",
  zones:
    "Deux clics posent deux coins opposés, comme pour un rectangle, mais le résultat découpe la zone de prix en trois bandes horizontales :\n\n- au-dessus de la plus haute des deux limites, une bande positive ;\n- en dessous de la plus basse, une bande négative ;\n- entre les deux, une bande neutre.\n\nChacune reçoit son propre remplissage, avec par défaut une couleur de hausse, une couleur de baisse et une teinte neutre, chacune modifiable indépendamment. Les deux traits horizontaux qui délimitent les bandes sont toujours visibles ; les côtés gauche et droit du rectangle sont masqués par défaut, précisément parce que les bandes positive et négative se lisent comme des régions ouvertes et non comme une boîte fermée — ils peuvent être réaffichés dans la fenêtre d'édition.\n\nL'outil sert à poser un cadre de décision plutôt qu'un simple repère : au-dessus de tel prix le scénario est validé, en dessous de tel autre il est invalidé, entre les deux il n'y a rien à faire. C'est aussi le tracé adapté à une zone de neutralité autour d'un prix d'entrée, ou à un couloir toléré autour d'un objectif.",
  elbowArrow:
    "Flèche brisée à segments multiples, construite clic par clic : chaque clic ajoute un sommet et l'outil reste actif indéfiniment, contrairement à tous les autres tracés qui se referment après un nombre de points fixé à l'avance. C'est la touche Échap qui valide et dessine la flèche avec les points posés jusque-là.\n\nLes sommets sont reliés par des segments droits et une seule pointe de flèche est ajoutée au tout dernier point : le sens de lecture est donc celui du tracé, du premier clic vers le dernier. Rien n'oblige les segments à former des angles droits — la forme dépend uniquement de l'endroit où l'on clique, ce qui permet aussi bien un coude à angle droit qu'une flèche libre en plusieurs tronçons.\n\nSon usage est l'annotation : désigner un élément précis du graphique en partant d'une zone dégagée, contourner des bougies ou d'autres tracés au lieu de passer par-dessus, ou relier deux événements distants sans masquer ce qui se trouve entre eux. Chaque sommet reste déplaçable individuellement après validation.",
  brush:
    "Tracé à main levée : on maintient le bouton enfoncé et l'on dessine, le trait suivant le curseur en échantillonnant sa trajectoire. Contrairement à tous les autres outils, il ne se pose pas par clics successifs mais par un seul geste continu, du point où le bouton est enfoncé à celui où il est relâché.\n\nC'est l'outil de l'annotation libre, celui qui permet d'entourer une zone, de souligner une portion de courbe, de barrer un scénario abandonné ou d'esquisser une forme qu'aucun tracé géométrique ne rendrait — typiquement lorsqu'on prépare une capture d'écran à commenter ou que l'on annote un graphique pour soi-même.\n\nLe trait peut comporter des dizaines de points, aussi n'est-il pas modifiable point par point : il se déplace uniquement d'un seul bloc, et se supprime pour être refait s'il ne convient pas. Sa couleur et son épaisseur restent réglables comme celles de n'importe quel autre tracé.",
  arrowUp:
    "Un seul clic pose un petit triangle pointant vers le haut, juste sous l'endroit désigné. C'est un repère purement visuel, sans texte ni calcul : il sert à marquer un point d'intérêt haussier — un signal d'achat, un creux identifié, une bougie de retournement, l'endroit où une position a été prise.\n\nSon intérêt est de rester lisible même sur un graphique chargé, là où une ligne supplémentaire ajouterait du bruit. On l'utilise souvent en série pour repérer plusieurs occurrences d'une même configuration et vérifier d'un coup d'œil si elle a effectivement été suivie d'effet.\n\nLe repère se déplace ensuite librement, et sa couleur se change comme celle de n'importe quel tracé ; une étiquette de texte peut lui être ajoutée depuis la fenêtre d'édition si le symbole seul ne suffit pas.",
  arrowDown:
    "Un seul clic pose un petit triangle pointant vers le bas, juste au-dessus de l'endroit désigné — l'exact symétrique de la flèche haut. Il marque un point d'intérêt baissier : signal de vente, sommet identifié, bougie de retournement, sortie de position, ou simplement un endroit à ne pas oublier lors d'une relecture.\n\nUtilisé conjointement avec la flèche haut, il permet de reconstituer visuellement une série d'entrées et de sorties sur l'historique et d'en juger la cohérence, sans avoir à passer par un outil de position complet.\n\nComme son homologue, il reste déplaçable, sa couleur est modifiable, et une étiquette de texte peut lui être associée depuis la fenêtre d'édition.",
  arrowLine:
    "Deux clics tracent un segment droit identique à une ligne de tendance, mais terminé par une pointe de flèche à son extrémité. Le sens compte donc : le premier clic est l'origine, le second la cible désignée.\n\nCe n'est pas un outil d'analyse mais d'explication — il sert à montrer un mouvement (« de là à là »), à pointer une bougie ou un niveau depuis une zone dégagée, ou à relier une annotation à ce qu'elle commente. Il est particulièrement utile lorsqu'un graphique est destiné à être partagé ou commenté, là où une ligne sans direction laisserait le lecteur deviner ce qui est désigné.\n\nLa position de la pointe suit le sens du tracé à l'écran, et la fenêtre d'édition permet ensuite d'ajouter ou de retirer une pointe à chaque extrémité, ainsi que d'associer un texte au segment.",
  fibonacci:
    "Deux clics définissent le mouvement à analyser : le premier point vaut 0 %, le second 100 %. L'écart de prix entre les deux est ensuite découpé selon les ratios standard — 0, 23,6 %, 38,2 %, 50 %, 61,8 %, 78,6 % et 100 % — et chaque niveau est tracé comme un segment horizontal couvrant la plage de dates du tracé, étiqueté de son ratio et du prix correspondant.\n\nOn l'applique classiquement à une jambe de tendance nette, en partant du creux vers le sommet pour une hausse : les niveaux obtenus indiquent alors jusqu'où le prix pourrait retracer avant de repartir. Les zones les plus surveillées sont 38,2 % pour une correction superficielle dans une tendance forte, 50 % et 61,8 % pour une correction ordinaire ; un retracement qui dépasse durablement 61,8 %, et a fortiori 78,6 %, remet en cause l'idée d'une simple correction.\n\nUn point mérite d'être gardé à l'esprit : ces niveaux n'ont aucune propriété mécanique, ils fonctionnent surtout parce que beaucoup d'intervenants les regardent, et leur pertinence dépend entièrement du choix des deux points de départ. Ceux-ci restent déplaçables, ce qui permet d'ajuster le tracé et de voir aussitôt tous les niveaux se recalculer.",
  fibonacciExtension:
    "Trois clics — A, B puis C — servant à projeter un objectif de prix au-delà d'un mouvement déjà accompli. A et B délimitent la jambe de référence, C marque la fin de la correction qui l'a suivie. Les niveaux sont ensuite projetés à partir de C, chacun valant une fraction de l'amplitude de prix de la jambe A-B : 0, 38,2 %, 61,8 %, 100 %, 138,2 %, 161,8 %, 200 % et 261,8 %.\n\nAutrement dit, le niveau 100 % correspond à une seconde jambe de même ampleur que la première partant de C, et le niveau 161,8 % à une jambe une fois et demie plus longue. C'est l'outil complémentaire du retracement : celui-ci indique où la correction pourrait s'arrêter, l'extension où le mouvement suivant pourrait aller. Les niveaux 100 % et 161,8 % sont les objectifs les plus couramment retenus pour des prises de bénéfice partielles.\n\nComme pour le retracement, la fiabilité dépend entièrement du choix des trois points, et les niveaux valent comme zones à surveiller et non comme cibles garanties. Les trois points restent déplaçables après tracé.",
  elliottImpulse:
    "Six clics posent les points 0 à 5, formant les cinq segments d'une vague impulsive au sens de la théorie d'Elliott : trois vagues dans le sens de la tendance (1, 3 et 5) entrecoupées de deux corrections (2 et 4). Chaque sommet est numéroté directement sur le graphique. C'est un outil de comptage, pas de calcul : il ne vérifie pas la validité de la structure, il la matérialise pour permettre de la lire et de la comparer.\n\nTrois règles de la théorie restent à la charge de celui qui trace :\n\n- la vague 2 ne doit jamais retracer entièrement la vague 1 ;\n- la vague 3 ne doit jamais être la plus courte des trois vagues d'impulsion ;\n- la vague 4 ne doit pas empiéter sur le territoire de prix de la vague 1.\n\nUn comptage qui viole l'une de ces règles doit être refait.\n\nL'intérêt pratique est de situer le mouvement en cours dans une structure d'ensemble : identifier qu'on se trouve en vague 4 conduit à anticiper une dernière poussée, tandis qu'une vague 5 achevée signale l'approche d'une correction de plus grande ampleur. La subjectivité du comptage est réelle et assumée — deux analystes comptent rarement de la même manière, et chaque point reste déplaçable pour ajuster une lecture.",
  elliottCorrection:
    "Quatre clics posent les points 0, A, B et C, formant les trois segments d'une vague correctrice — le contre-mouvement qui suit une impulsion. Chaque sommet porte sa lettre sur le graphique.\n\nLa structure typique est un zigzag : une première jambe A contre la tendance, un rebond partiel B, puis une jambe C qui prolonge le mouvement de A, souvent jusqu'à une amplitude comparable. D'autres formes existent — le plat, où B revient presque au point de départ, et le triangle, où les oscillations se resserrent — et le tracé les représente aussi bien, puisqu'il se contente de relier les points posés.\n\nSon usage principal est d'identifier la fin de la correction pour se repositionner dans le sens de la tendance principale : l'achèvement du point C est le moment que l'on cherche à situer. Il se combine naturellement avec la vague impulsive, la séquence complète en cinq vagues suivie d'une correction en trois formant le cycle de base de la théorie. Comme pour l'impulsion, l'interprétation est subjective et les quatre points restent déplaçables.",
  headShoulders:
    "Sept clics posent la figure complète, dans l'ordre du tracé :\n\n- un creux de départ ;\n- l'épaule gauche ;\n- le creux intermédiaire ;\n- la tête ;\n- le second creux ;\n- l'épaule droite ;\n- un dernier point de confirmation.\n\nLes sept sommets sont numérotés et les trois principaux — épaule gauche, tête, épaule droite — reçoivent en plus leur propre étiquette.\n\nLa ligne de cou n'est pas un point que l'on place : elle est déduite automatiquement des deux creux situés de part et d'autre de la tête, et tracée en pointillés. Elle se prolonge vers la droite au-delà du dernier point tant que celui-ci ne l'a pas franchie par le bas ; dès que la cassure est actée, elle cesse de se projeter, la figure étant résolue. Une ligne horizontale marque en outre le niveau de la tête, et la zone comprise entre la figure et la ligne de cou est remplie.\n\nLa lecture classique est celle d'un retournement de tendance haussière : la tête marque le dernier excès, l'épaule droite l'échec à le dépasser, et c'est la cassure de la ligne de cou qui valide la figure — pas l'épaule droite seule. L'objectif de prix usuel se mesure en reportant sous la ligne de cou la hauteur qui sépare celle-ci de la tête. Les sept points restent déplaçables pour ajuster le tracé.",
  cupHandle:
    "Cinq clics posent la figure, chacun étiqueté sur le graphique :\n\n- A marque le début de la tasse ;\n- B son fond ;\n- C la fin de la tasse et le début de l'anse ;\n- D le fond de l'anse ;\n- E sa fin.\n\nLa figure décrit une longue consolidation en forme d'arrondi — pas en V, la lenteur de la formation faisant partie de sa définition — suivie d'un repli court et peu profond juste sous le sommet retrouvé. Les proportions comptent : C doit revenir approximativement au niveau de A, et l'anse doit rester nettement moins profonde que la tasse, un repli aussi marqué que celle-ci n'étant plus une anse mais une nouvelle jambe de baisse.\n\nLa lecture est haussière : la tasse traduit l'absorption progressive des vendeurs, l'anse une dernière prise de bénéfices, et c'est le franchissement du niveau de C qui déclenche la figure. L'objectif usuel s'obtient en reportant la profondeur de la tasse au-dessus du point de cassure. Les cinq points restent déplaçables après tracé, ce qui permet de faire épouser la forme à la structure réelle.",
  forecast:
    "Deux clics — un point de départ, un point d'arrivée — tracent non pas une droite mais une courbe bombée reliant les deux, avec une pointe à l'extrémité. Les deux extrémités sont annotées de leur prix et de leur date, et l'extrémité d'arrivée affiche en plus la variation de prix et le temps écoulé depuis le départ.\n\nLa forme courbe est délibérée : elle distingue immédiatement cet outil d'une ligne de tendance et évite qu'un scénario projeté ne soit confondu avec un support ou une résistance.\n\nC'est un outil de narration, pas de calcul — il sert à esquisser une hypothèse de trajectoire (« si le prix tient ce niveau, je le vois rejoindre celui-ci d'ici la fin du mois ») et surtout à la conserver pour la confronter plus tard à ce qui s'est réellement produit. C'est l'usage le plus utile qu'on puisse en faire : accumuler ses propres projections passées et vérifier honnêtement lesquelles se sont réalisées. Les deux points restent déplaçables, les étiquettes se recalculant aussitôt.",
  rangeForecast:
    "Deux clics suffisent : le premier fixe le point de départ, le second donne la direction et l'horizon. À partir de ce second clic, l'outil calcule automatiquement deux objectifs encadrant symétriquement le prix visé, à cinq pour cent au-dessus et en dessous, ce qui produit trois branches partant du même point — vers le Max, vers le Min, et vers leur moyenne, tracée en pointillés. La zone triangulaire comprise entre les branches Max et Min est remplie, et chaque extrémité est annotée de son prix et de son écart en pourcentage par rapport au départ.\n\nC'est l'outil de la projection honnête : au lieu d'un objectif unique qui suggère une précision illusoire, il exprime un scénario sous forme de fourchette, ce qui correspond bien mieux à la nature d'une anticipation de marché. Il convient particulièrement pour formuler une hypothèse avant une publication de résultats ou une échéance connue.\n\nLe Max et le Min sont ensuite librement déplaçables et indépendants l'un de l'autre — la fourchette n'a donc aucune obligation de rester symétrique — et la branche moyenne se replace toute seule entre les deux.",
  longPosition:
    "Un seul clic pose une position longue complète : le point cliqué devient le prix d'entrée, tandis que l'objectif et le stop sont calculés immédiatement de part et d'autre — l'objectif au-dessus, le stop en dessous, avec par défaut un gain visé de dix pour cent contre un risque de cinq pour cent, soit un rapport de deux pour un.\n\nLe tracé se compose de deux bandes horizontales partant de l'entrée : celle de l'objectif toujours dans la couleur de hausse, celle du stop toujours dans la couleur de baisse, indépendamment de la position réelle des prix, puisque c'est le rôle de chaque niveau qui compte et non sa valeur. Chaque bande est annotée de son prix et de son écart en pourcentage par rapport à l'entrée, et l'entrée elle-même affiche le rapport gain/risque effectif.\n\nC'est là tout l'intérêt de l'outil : en déplaçant l'objectif et le stop pour les caler sur des niveaux techniques réels — une résistance au-dessus, un support sous lequel le scénario serait invalidé — on voit le rapport gain/risque se recalculer en direct, ce qui permet d'écarter une opération avant même de la prendre lorsque le rapport devient défavorable. Les deux niveaux se déplacent en prix comme en date, la date fixant l'horizon envisagé.",
  shortPosition:
    "Un seul clic pose une position courte complète, symétrique de la position longue : le point cliqué devient l'entrée, l'objectif est placé en dessous et le stop au-dessus, puisqu'une vente à découvert gagne quand le prix baisse. Les proportions par défaut sont les mêmes — dix pour cent de gain visé contre cinq pour cent de risque, soit un rapport de deux pour un.\n\nLa bande de l'objectif conserve la couleur de gain et celle du stop la couleur de perte quelle que soit leur position à l'écran, de sorte que la lecture reste immédiate. Chaque bande affiche son prix et son écart en pourcentage par rapport à l'entrée, et l'entrée indique le rapport gain/risque courant, recalculé à chaque déplacement.\n\nLa démarche est la même que pour une position longue : caler le stop juste au-dessus d'une résistance qui invaliderait le scénario, l'objectif sur un support crédible, et juger le rapport obtenu avant de décider. Les deux niveaux restent déplaçables en prix comme en date.",
  text: "Un clic ouvre une zone de saisie directement sur le graphique, à l'endroit désigné : on tape le texte et il est posé, sans passer par une fenêtre intermédiaire. C'est l'annotation la plus dépouillée qui soit — pas de cadre, pas de flèche, pas de connecteur, juste des caractères posés sur le graphique. La taille, la graisse, l'italique, la couleur et un fond éventuel se règlent ensuite dans la fenêtre d'édition.\n\nIl sert à tout ce qui doit être écrit plutôt que dessiné : nommer une figure identifiée, noter le raisonnement derrière une décision, inscrire un objectif chiffré, dater un contexte. Sur un graphique destiné à être relu des semaines plus tard ou partagé, c'est souvent le tracé le plus utile de tous, parce que c'est le seul qui explique le pourquoi. Le texte se déplace ensuite librement.",
  comment:
    "Un clic ouvre une saisie de texte à l'endroit désigné, et le résultat s'affiche dans une bulle arrondie dont la pointe désigne précisément le point cliqué — la différence avec le texte simple, qui repose nu sur le graphique. La bulle possède toujours un fond, coloré par défaut avec la teinte d'accentuation et modifiable, la couleur du texte s'ajustant pour rester lisible.\n\nLe fond garantit que le commentaire reste lisible même par-dessus des bougies ou des indicateurs, là où un texte nu se confond avec ce qui se trouve derrière. La pointe, elle, lève toute ambiguïté sur ce qui est commenté, ce qui compte dès que plusieurs annotations cohabitent.\n\nC'est le tracé à privilégier quand le graphique est destiné à être partagé ou relu par quelqu'un d'autre : il ressemble à une note collée et se lit comme telle, sans risque de confusion avec un élément d'analyse.",
  note: "Deux clics : le premier place l'ancre — un petit repère creux posé sur l'élément à commenter — le second détermine où s'ouvre la zone de saisie, donc où le texte viendra se placer. Les deux points sont reliés par un trait droit.\n\nL'intérêt par rapport à un commentaire simple est de pouvoir écarter le texte de la zone dense du graphique tout en gardant un lien visuel explicite avec ce qu'il désigne : on ancre sur la bougie ou le niveau concerné, puis on installe la note dans une marge dégagée. C'est le tracé adapté aux annotations un peu longues, qui recouvriraient les prix si elles étaient posées directement dessus.\n\nL'ancre et le texte se déplacent indépendamment, le trait de liaison suivant automatiquement, ce qui permet de réorganiser plusieurs notes sans perdre leurs rattachements.",
  priceNote:
    "Identique à la note dans son fonctionnement — un premier clic pour l'ancre, un second pour l'emplacement du texte, un trait reliant les deux — à une différence près : l'étiquette affiche systématiquement le prix de l'ancre en tête, avant le texte saisi.\n\nCe prix n'est pas figé au moment du tracé, il est relu à chaque affichage à partir de la position réelle de l'ancre : déplacer celle-ci met donc la valeur à jour toute seule. C'est ce qui distingue l'outil d'une note ordinaire à laquelle on aurait tapé un prix à la main, qui deviendrait fausse au premier ajustement.\n\nOn l'utilise pour tout ce qui doit rester chiffré et exact : marquer un niveau de résistance en le nommant, noter un prix d'entrée envisagé, documenter un point de cassure avec sa valeur. Ancre et texte restent déplaçables séparément.",
  pin: "Un seul clic plante une épingle dont la pointe touche exactement l'endroit désigné. C'est le repère le plus dépouillé de tous : pas de texte, pas de trait, pas de valeur affichée — juste une marque visuelle.\n\nSon usage est celui d'un signet : retrouver rapidement un endroit sur lequel on souhaite revenir, marquer une bougie repérée au cours d'une exploration de l'historique, ou baliser une série de points comparables pour les retrouver d'un coup d'œil en dézoomant. Il ne prétend rien démontrer, ce qui est précisément son avantage sur un graphique déjà chargé de tracés d'analyse : il n'ajoute aucune information susceptible d'être confondue avec un niveau ou une projection.\n\nSa taille est fixe, indépendante de l'épaisseur de trait ; seule sa couleur se règle, et l'épingle se déplace librement.",
  flagMark:
    "Un seul clic plante un petit drapeau dont le pied repose sur l'endroit désigné. Comme l'épingle, c'est un repère purement visuel, sans texte ni valeur.\n\nLa différence est d'usage plus que de fonction : là où l'épingle sert plutôt de signet personnel, le drapeau évoque un jalon ou un événement, ce qui en fait un bon marqueur de dates remarquables — le début d'une campagne, une publication, la prise d'une décision. Utiliser deux symboles distincts permet surtout de séparer deux catégories de repères sur un même graphique et de les distinguer sans avoir à lire quoi que ce soit.\n\nSa taille est fixe et seule sa couleur est réglable, ce qui permet aussi de coder plusieurs types d'événements par la teinte. Le repère se déplace ensuite librement.",
  signpost:
    "Un clic ouvre une saisie de texte à l'endroit désigné, et l'étiquette obtenue est reliée par un trait vertical en pointillés jusqu'à la clôture de la bougie située à cette date, où un petit point marque le rattachement.\n\nLe rattachement n'est pas figé : la bougie concernée est déterminée à chaque affichage, si bien que déplacer l'étiquette le long de l'axe des dates fait suivre le connecteur, qui reste toujours accroché à la bougie effectivement située dessous. C'est ce qui distingue le panneau du texte simple ou de la note : le lien est temporel et automatique, alors qu'une note pointe vers un point fixé une fois pour toutes.\n\nOn l'utilise pour horodater un événement en le nommant — une publication de résultats, une annonce, un changement de dirigeant — en plaçant l'étiquette au-dessus des bougies, dans une zone dégagée, sans perdre le lien avec la date exacte. La mise en forme du texte se règle dans la fenêtre d'édition.",
  priceLabel:
    "Un seul clic pose une bulle affichant le prix du point désigné. Il n'y a pas de texte à saisir : le contenu de la bulle est le prix lui-même, relu à chaque affichage à partir de la position réelle du repère, si bien que déplacer la bulle met la valeur à jour instantanément.\n\nC'est ce qui en fait l'outil le plus direct pour lire et conserver une valeur précise ailleurs que sur l'axe : on la pose sur un sommet, un creux, une clôture ou un niveau projeté, et le chiffre reste affiché sur le graphique. Il rend service dès qu'il faut comparer plusieurs niveaux sans passer par le survol du curseur, ou préparer une capture d'écran où les valeurs clés doivent apparaître.\n\nLa bulle reprend la même forme que le commentaire, à ceci près que son contenu est calculé et non écrit.",
  table:
    "Deux clics posent les deux coins opposés d'un tableau, découpé en cellules d'égale taille — trois lignes et trois colonnes par défaut, ce nombre étant modifiable dans la fenêtre d'édition. Chaque cellule s'édite directement sur le graphique par un double-clic, sans passer par une fenêtre : on tape le contenu et on valide, cellule par cellule.\n\nC'est l'outil des informations structurées qu'aucun tracé ne sait porter :\n\n- un récapitulatif de scénario avec ses niveaux d'entrée, d'objectif et de stop ;\n- une liste de dates à surveiller ;\n- une comparaison entre plusieurs hypothèses ;\n- un rappel de règles personnelles.\n\nSur un graphique destiné à être partagé ou relu plus tard, il tient lieu de légende.\n\nUne précision utile : les cellules sont repérées par leur position dans la grille, donc modifier le nombre de colonnes après coup redistribue les contenus existants — mieux vaut fixer les dimensions avant de remplir. Le tableau se déplace d'un bloc et se redimensionne par ses deux coins.",
  measure:
    "Deux clics délimitent la mesure : un point de départ, puis un point d'arrivée, après quoi l'outil se désactive tout seul — contrairement aux autres, qui restent actifs jusqu'à ce qu'on en sorte.\n\nLe résultat s'affiche sous forme d'un rectangle translucide entre les deux points, vert si le prix a monté du premier au second, rouge s'il a baissé, accompagné d'un encart chiffré donnant quatre valeurs :\n\n- la variation en pourcentage ;\n- le nombre de bougies écoulées ;\n- le nombre de jours calendaires ;\n- l'écart de prix absolu en points.\n\nLa distinction entre bougies et jours calendaires a son importance, puisque week-ends et jours fériés créent un décalage systématique entre les deux.\n\nC'est l'outil à dégainer pour comparer objectivement deux mouvements — vérifier si le rebond en cours est comparable au précédent, en amplitude comme en durée — ou pour évaluer rapidement ce que représenterait un objectif en pourcentage.\n\nLa mesure n'est pas enregistrée parmi les dessins : elle reste affichée à l'écran, avec ses deux poignées déplaçables et son rectangle déplaçable d'un bloc, jusqu'à ce qu'Échap l'efface ou qu'une nouvelle mesure la remplace.",
};
