import type { ReactNode } from "react";

/** Which book an order is sent to. Two words that must never be confused, which is why they are a
 *  union and not a boolean: `live: false` reads as an absence, and an absence is what a bug looks
 *  like. */
export type BrokerEnvironment = "demo" | "live";

/** One field a broker's connection form asks for.
 *
 *  Declared by the adapter rather than hard-coded here, because no two brokers ask for the same
 *  things — an API key and an account identifier for one, an OAuth redirect for another. The
 *  library renders these, hands the values straight to `connect`, and **never stores them**: not in
 *  state that outlives the modal, not in `localStorage`, not in a callback. A credential this
 *  library kept would be a credential in a browser, readable by anyone who opens the devtools. */
export interface BrokerCredentialField {
  name: string;
  label: string;
  /** `password` masks the input and keeps it out of autofill history. */
  type: "text" | "password";
  placeholder?: string;
  /** Shown under the field, and in the `?` beside it. Say where the value comes from — "Console →
   *  Paramètres → Clé d'API" — rather than restating the label. */
  hint?: string;
  required?: boolean;
}

/** An account the connected session can trade on. */
export interface BrokerAccount {
  id: string;
  label: string;
  currency: string;
  /** Free to open new positions with, in `currency`. Shown beside the order ticket's own risk
   *  figure so the two can be compared without leaving the panel. */
  available?: number;
  balance?: number;
}

/** What the adapter hands back from `connect`. Opaque to this library: it is passed to every other
 *  adapter call and never read, which is what lets an adapter keep a token, a cookie jar, or
 *  nothing at all behind it. */
export interface BrokerSession {
  /** Shown in the panel so it is always clear *which* connection is live. */
  accountId: string;
  environment: BrokerEnvironment;
  /** The adapter's own handle. Never inspected here. */
  handle: unknown;
}

/** What a symbol is called at this broker, and what it may be traded in.
 *
 *  A chart's own symbol ("MSFT") is not a dealable instrument: a broker has its own identifier, its
 *  own minimum size, its own step. Resolving that is the adapter's job, and an unresolved symbol
 *  must stop the ticket rather than be guessed at. */
export interface BrokerMarket {
  /** The adapter's own identifier for the instrument. */
  epic: string;
  label: string;
  currency: string;
  /** Smallest size that may be traded, and the step between valid sizes. */
  minSize: number;
  sizeStep: number;
  /** Smallest price increment, for rounding a stop or a limit to something the broker accepts. */
  tickSize?: number;
  /** What one unit of size is worth per tick, when the adapter knows it — the only honest way to
   *  turn "stop 40 ticks away" into a figure in the account's currency. Absent, the ticket says so
   *  rather than inventing one. */
  tickValue?: number;
  /** False when the instrument cannot be traded right now. The ticket refuses to submit. */
  tradable: boolean;
}

export type BrokerOrderSide = "buy" | "sell";
/** `market` fills now at whatever the book offers. `limit` waits for a price. */
export type BrokerOrderType = "market" | "limit";

/** Everything needed to place one order, as the ticket assembled it.
 *
 *  Every field is explicit — nothing is defaulted inside the adapter — so that what the confirmation
 *  screen showed is exactly what was sent. */
export interface BrokerOrderRequest {
  /** Generated by this library, once, when the ticket is first submitted. Sent unchanged on every
   *  attempt so a broker that honours it cannot open two positions from one intent — a double
   *  click, a retry after a timeout whose order actually landed. An adapter that cannot pass it
   *  through should say so in its docs; the library has no other protection against duplicates. */
  clientOrderId: string;
  epic: string;
  side: BrokerOrderSide;
  type: BrokerOrderType;
  size: number;
  /** `type: "limit"` only. */
  limitPrice?: number;
  /** Absolute prices, not distances: a distance has to be turned into a price by someone, and
   *  doing it here means the number on the confirmation screen is the number sent. */
  stopLoss?: number;
  takeProfit?: number;
  /** What produced this order, for the journal: a strategy's id and name, or nothing for one typed
   *  by hand. */
  origin?: { scriptId: string; scriptName: string };
}

export interface BrokerOrderResult {
  /** The broker's own reference, when it gave one. */
  dealId?: string;
  status: "accepted" | "rejected";
  /** Filled price, when the broker reported one. */
  price?: number;
  /** Required when `rejected`, and shown verbatim: a rejection the user cannot read is a rejection
   *  they will retry blindly. */
  reason?: string;
}

export interface BrokerPosition {
  id: string;
  epic: string;
  label: string;
  side: BrokerOrderSide;
  size: number;
  openPrice: number;
  /** In the account's currency, when the adapter reports it. */
  profit?: number;
  stopLoss?: number;
  takeProfit?: number;
  openedAt?: number;
}

/** What a broker must provide for this library to trade through it.
 *
 *  **This library implements none of these and ships no broker.** It renders the forms, assembles
 *  the orders, enforces the limits and keeps the journal; every call that leaves the browser is the
 *  host's. That is not a limitation to work around — it is the point. A front-end library that held
 *  broker credentials would hold them in a browser, and a front-end library that placed orders
 *  itself would place them from a page anyone can open the devtools on.
 *
 *  Every method may reject. A rejection is shown to the user and never retried on its own — see
 *  `BrokerOrderRequest.clientOrderId` for why a retry is the caller's decision, not this library's.
 */
export interface BrokerAdapter {
  /** Stable, unique among the adapters given to the workspace. Used as the picker's own value. */
  id: string;
  /** What the picker shows. */
  label: string;
  /** Optional mark beside the name in the picker. */
  logo?: ReactNode;
  /** Which environments this adapter can reach. A broker with no practice account declares
   *  `["live"]`, and the connection modal then says so rather than offering a demo that does not
   *  exist. */
  environments: BrokerEnvironment[];
  credentialFields: BrokerCredentialField[];
  /** One sentence under the picker: what this connection actually is, and where the credentials
   *  go. Shown before anything is typed. */
  notice?: string;

  connect(values: Record<string, string>, environment: BrokerEnvironment): Promise<BrokerSession>;
  disconnect(session: BrokerSession): Promise<void>;
  accounts(session: BrokerSession): Promise<BrokerAccount[]>;
  /** Resolves a chart symbol to a dealable instrument, or null when this broker does not offer it.
   *  Null stops the ticket: an order on a guessed instrument is worse than no order. */
  resolveMarket(session: BrokerSession, symbol: string): Promise<BrokerMarket | null>;
  placeOrder(session: BrokerSession, order: BrokerOrderRequest): Promise<BrokerOrderResult>;
  positions(session: BrokerSession): Promise<BrokerPosition[]>;
  /** Closes all of a position, or `size` of it. */
  closePosition(session: BrokerSession, positionId: string, size?: number): Promise<BrokerOrderResult>;
}
