import { useEffect, useMemo, useRef, useState } from "react";
import { CloseIcon, SparkleIcon } from "../../../../icons";
import type { AiChartContext } from "../interfaces/AiChartContext.interface";
import type { AiSend, AiServerTool } from "../interfaces/AiMessage.interface";
import { useAiAssistant } from "../useAiAssistant";
import { filterSlashCommands, slashCommandsFor, slashQueryAt, type SlashCommand } from "../slashCommands";
import "./AiPanel.css";
import type { ScriptReport } from "../../scripting/interfaces/ScriptReport.interface";
import { ReportPrintWindow } from "../../scripting/components/ReportPrintWindow";
import { ReportView } from "../../scripting/components/ReportView";
import { Modal } from "../../../../primitives/Modal";

export interface AiPanelProps {
  open: boolean;
  onClose: () => void;
  chart: AiChartContext;
  /** Null when the caller configured no transport — the panel then explains that rather than
   *  offering a box that could never answer. */
  send: AiSend | null;
  serverTools: AiServerTool[];
  /** Extra symbols to offer in the `/` menu, beyond the chart's own — a watchlist, typically. */
  symbols: string[];
}

const PLACEHOLDER = "Posez une question, ou tapez / pour une commande";

/** The assistant, docked to the right of the chart.
 *
 *  A panel rather than a modal: everything it is asked about is on the chart behind it, and a
 *  dialog that covers the very thing being discussed would have to be dismissed to check its own
 *  answers. */
export function AiPanel({ open, onClose, chart, send, serverTools, symbols }: AiPanelProps) {
  const { transcript, busy, ask, stop, reset } = useAiAssistant({ chart, send, serverTools });
  const [draft, setDraft] = useState("");
  const [menuIndex, setMenuIndex] = useState(0);
  const inputRef = useRef<HTMLTextAreaElement | null>(null);
  const scrollRef = useRef<HTMLDivElement | null>(null);
  const [caret, setCaret] = useState(0);
  /** The `/` the menu is currently dismissed for. Escape closes the menu without touching the text
   *  — the slash the user typed is theirs to keep — so "closed" cannot be expressed by moving the
   *  caret, which the very next keystroke would undo. Cleared as soon as the query changes, so
   *  typing on carries the menu back. */
  const [dismissed, setDismissed] = useState<string | null>(null);

  const commands = useMemo(() => slashCommandsFor(chart, symbols), [chart, symbols]);
  /** Every script whose last run produced a document. Read from the run outputs rather than kept
   *  here, so a report regenerated by a second run replaces the first instead of stacking. */
  const reports = useMemo(
    () =>
      chart.scripts
        .map((script) => ({ script, report: chart.runOutputs[script.id]?.result?.report ?? null }))
        .filter((entry): entry is { script: (typeof chart.scripts)[number]; report: ScriptReport } => entry.report !== null),
    // `chart` itself is a fresh object every render (see useAiChartContext) — depending on it
    // would rebuild this list on every commit, which is exactly what the two fields it actually
    // reads are here to avoid.
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [chart.scripts, chart.runOutputs],
  );
  const [openReport, setOpenReport] = useState<ScriptReport | null>(null);
  const [printTarget, setPrintTarget] = useState<{ report: ScriptReport; target: Window } | null>(null);

  /** Opened inside the click — a `window.open` from anywhere else is blocked as a popup. */
  function printReport(report: ScriptReport) {
    const target = window.open("", "", "width=900,height=1000");
    if (target === null) return;
    setPrintTarget({ report, target });
  }
  const slash = slashQueryAt(draft, caret);
  const matches = slash === null ? [] : filterSlashCommands(commands, slash.query).slice(0, 8);
  const menuOpen = slash !== null && matches.length > 0 && dismissed !== slash.query;

  // Follows the conversation as it grows. `scrollTop` rather than scrollIntoView: the panel is its
  // own scroller, and scrolling an element into view would drag the whole page on a narrow layout.
  useEffect(() => {
    const el = scrollRef.current;
    if (el) el.scrollTop = el.scrollHeight;
  }, [transcript]);

  useEffect(() => {
    if (open) inputRef.current?.focus();
  }, [open]);

  useEffect(() => {
    setMenuIndex(0);
    setDismissed((current) => (current === slash?.query ? current : null));
  }, [slash?.query]);

  if (!open) return null;

  function applyCommand(command: SlashCommand) {
    if (slash === null) return;
    const caretMark = command.template.indexOf("…");
    const next = draft.slice(0, slash.from) + command.template + draft.slice(caret);
    setDraft(next);
    const position = slash.from + (caretMark === -1 ? command.template.length : caretMark);
    // After the state has landed, so the box has the new text to place a caret in.
    requestAnimationFrame(() => {
      const el = inputRef.current;
      if (!el) return;
      el.focus();
      el.setSelectionRange(position, position + (caretMark === -1 ? 0 : 1));
      setCaret(position);
    });
  }

  function submit() {
    if (busy || draft.trim() === "") return;
    void ask(draft);
    setDraft("");
    setCaret(0);
  }

  return (
    <aside className="lq-ai" aria-label="Assistant">
      <header className="lq-ai__header">
        <span className="lq-ai__title">
          <SparkleIcon size={13} /> Assistant
        </span>
        <span className="lq-ai__header-actions">
          {transcript.length > 0 && (
            <button type="button" className="lq-ai__header-button" onClick={reset} title="Effacer la conversation">
              Effacer
            </button>
          )}
          <button type="button" className="lq-ai__header-button" onClick={onClose} aria-label="Fermer l'assistant" title="Fermer">
            <CloseIcon size={12} />
          </button>
        </span>
      </header>

      <div className="lq-ai__scroll" ref={scrollRef}>
        {send === null && (
          <p className="lq-ai__notice">
            Aucun moteur d'IA n'est configuré. L'application doit fournir la prop <code>ai</code> du graphique — soit une clé d'API, soit sa
            propre fonction d'envoi.
          </p>
        )}
        {transcript.length === 0 && send !== null && (
          <div className="lq-ai__intro">
            <p>Je vois ce que montre le graphique et je peux agir dessus : indicateurs, dessins, scripts, analyses.</p>
            <ul>
              <li>« Affiche le volume, une SMA 20 et une EMA 50 »</li>
              <li>« Dessine les canaux entre le 10/10/2025 et le 05/02/2026 »</li>
              <li>« Sur la stratégie …, comment améliorer le Sharpe sans surajuster ? »</li>
              <li>« Écris une stratégie qui passe LONG quand … »</li>
            </ul>
            <p className="lq-ai__intro-hint">Tapez / pour viser un script, un symbole ou une commande.</p>
          </div>
        )}
        {transcript.map((entry) =>
          entry.role === "tool" ? (
            <details key={entry.id} className={["lq-ai__tool", entry.isError && "lq-ai__tool--error"].filter(Boolean).join(" ")}>
              <summary>{entry.isError ? `${entry.toolName} — échec` : entry.toolName}</summary>
              <pre>{entry.text}</pre>
            </details>
          ) : (
            <div
              key={entry.id}
              className={["lq-ai__message", `lq-ai__message--${entry.role}`, entry.isError && "lq-ai__message--error"]
                .filter(Boolean)
                .join(" ")}
            >
              {entry.text}
            </div>
          ),
        )}
        {/* Any report a script has produced, offered here rather than only in the editor: the
            assistant is where one gets asked for, so it is where the answer should be reachable —
            and opening the print window has to happen inside a real click, which a tool call is
            not. */}
        {reports.map(({ script, report }) => (
          <div key={script.id} className="lq-ai__report">
            <span className="lq-ai__report-title">{report.title}</span>
            <span className="lq-ai__report-meta">
              {report.symbol ? `${report.symbol} · ` : ""}
              {report.blocks.length} sections · {script.name}
            </span>
            <span className="lq-ai__report-actions">
              <button type="button" onClick={() => setOpenReport(report)}>
                Lire
              </button>
              <button type="button" onClick={() => printReport(report)}>
                Exporter en PDF
              </button>
            </span>
          </div>
        ))}
        {busy && <p className="lq-ai__busy">L'assistant travaille…</p>}
      </div>

      {openReport !== null && (
        <Modal open onClose={() => setOpenReport(null)} title={openReport.title} size="wide" footer={null}>
          <ReportView report={openReport} />
        </Modal>
      )}
      {printTarget !== null && (
        <ReportPrintWindow
          report={printTarget.report}
          target={printTarget.target}
          onDone={() => setPrintTarget(null)}
          themeSource={typeof document === "undefined" ? null : (document.querySelector(".lq-root") as HTMLElement | null)}
        />
      )}

      <div className="lq-ai__composer">
        {menuOpen && (
          <ul className="lq-ai__menu" role="listbox" aria-label="Commandes">
            {matches.map((command, i) => (
              <li key={command.key}>
                <button
                  type="button"
                  role="option"
                  aria-selected={i === menuIndex}
                  className={["lq-ai__menu-item", i === menuIndex && "lq-ai__menu-item--active"].filter(Boolean).join(" ")}
                  // Mousedown, not click: a click would first blur the textarea, and the caret this
                  // insertion is anchored to would be gone by the time the handler ran.
                  onMouseDown={(e) => {
                    e.preventDefault();
                    applyCommand(command);
                  }}
                >
                  <span className="lq-ai__menu-label">{command.label}</span>
                  <span className="lq-ai__menu-hint">{command.hint}</span>
                  <span className="lq-ai__menu-group">{command.group}</span>
                </button>
              </li>
            ))}
          </ul>
        )}
        <textarea
          ref={inputRef}
          className="lq-ai__input"
          value={draft}
          rows={3}
          placeholder={PLACEHOLDER}
          disabled={send === null}
          onChange={(e) => {
            setDraft(e.target.value);
            setCaret(e.target.selectionStart ?? e.target.value.length);
          }}
          onSelect={(e) => setCaret((e.target as HTMLTextAreaElement).selectionStart ?? 0)}
          onKeyDown={(e) => {
            if (menuOpen) {
              if (e.key === "ArrowDown") {
                e.preventDefault();
                setMenuIndex((i) => (i + 1) % matches.length);
                return;
              }
              if (e.key === "ArrowUp") {
                e.preventDefault();
                setMenuIndex((i) => (i - 1 + matches.length) % matches.length);
                return;
              }
              if (e.key === "Enter" || e.key === "Tab") {
                e.preventDefault();
                applyCommand(matches[menuIndex]);
                return;
              }
              if (e.key === "Escape") {
                e.preventDefault();
                setDismissed(slash?.query ?? null);
                return;
              }
            }
            if (e.key === "Enter" && !e.shiftKey) {
              e.preventDefault();
              submit();
            }
          }}
        />
        <div className="lq-ai__composer-actions">
          <span className="lq-ai__composer-hint">Entrée pour envoyer · Maj+Entrée pour un retour à la ligne</span>
          {busy ? (
            <button type="button" className="lq-ai__send" onClick={stop}>
              Arrêter
            </button>
          ) : (
            <button type="button" className="lq-ai__send" onClick={submit} disabled={send === null || draft.trim() === ""}>
              Envoyer
            </button>
          )}
        </div>
      </div>
    </aside>
  );
}
