import { addons } from "storybook/manager-api";
import { create } from "storybook/theming/create";
import buildInfo from "./buildInfo.json";

// Puts "v0.60.0 · 60b13ab+ · 2026-09-03 13:01" beside the sidebar logo, so a phone looking at a
// deployed build can be told apart from a laptop looking at the dev server at a glance. The
// version alone wouldn't do it — it only moves on a release, and most of the interesting drift
// happens between releases. Hence the short SHA (with a trailing "+" when the tree was dirty,
// which a dev server almost always is) and the build time.
//
// `buildInfo.json` is regenerated by scripts/storybook-build-info.mjs on every `storybook` and
// `build-storybook` run, and is gitignored: it describes one machine's build, not the repo.
addons.setConfig({
  theme: create({
    base: "light",
    brandTitle: `liseuse-dashboard-kit v${buildInfo.version} · ${buildInfo.commit} · ${buildInfo.builtAt}`,
  }),
});
