/** One reported period's worth of fundamentals — see `CandlestickChartProps.fundamentals`. Every
 *  metric is optional since not every caller has every figure for every period (a data source
 *  might report revenue quarterly but P/E only where it has trailing EPS, for instance); a metric
 *  missing at a given `date` just leaves that stretch of its own indicator pane unrendered (same
 *  "null until ready" convention as an indicator's own warm-up period) until the next report that
 *  does have it. Values persist (step function, not interpolated) from one `date` to the next
 *  since that's how a reported-quarterly-or-annually figure actually reads on a daily chart — flat
 *  until the next report changes it, not a smooth curve between two points that were never
 *  actually measured in between. */
export interface FundamentalDataPoint {
  date: Date;
  /** Free cash flow, in the instrument's own currency (not shares/percent). */
  freeCashFlow?: number;
  netIncome?: number;
  totalRevenue?: number;
  /** Net income ÷ revenue, as a percentage (e.g. 21.5 for 21.5%), not a 0-1 fraction. */
  netMargin?: number;
  /** Gross profit ÷ revenue, same percentage convention as `netMargin`. */
  grossMargin?: number;
  /** Price/earnings ratio — a plain number (e.g. 24.3), not a percentage. */
  peRatio?: number;
  /** Earnings per share, in the instrument's own currency. */
  eps?: number;
  /** Total debt ÷ total equity — a plain ratio (e.g. 0.8), not a percentage. */
  debtToEquity?: number;

  /* ---- What a company report needs, beyond what a pane plots ----
   *
   * Every one of these is optional, like everything above it: a caller reporting only revenue and
   * net income keeps working exactly as before. They exist because a report is a different demand
   * from a chart — a pane needs one series to draw, a report needs the line items that explain it:
   * what was earned, what it cost to keep earning it, what the state took, and what was left. Same
   * conventions throughout: currency amounts in the instrument's own currency, percentages as
   * whole numbers (21.5 for 21.5 %), ratios as plain numbers. */

  /** Revenue minus cost of goods sold. */
  grossProfit?: number;
  /** Operating income (EBIT) — what the business earned before financing and tax. */
  operatingIncome?: number;
  operatingMargin?: number;
  /** Earnings before interest, tax, depreciation and amortisation. */
  ebitda?: number;
  /** Capital expenditure. Reported positive here (an amount spent), whatever sign the source uses
   *  — a report that adds it to the cash-flow bridge should not have to guess the convention. */
  capex?: number;
  /** Cash generated by operations, before capital expenditure. */
  operatingCashFlow?: number;
  /** Research and development expense. */
  researchAndDevelopment?: number;
  /** Selling, general and administrative expense. */
  sellingGeneralAndAdministrative?: number;
  /** Income tax expense for the period. */
  taxExpense?: number;
  /** Tax expense ÷ pre-tax income, as a percentage. */
  effectiveTaxRate?: number;
  /** Interest paid on debt. */
  interestExpense?: number;

  totalAssets?: number;
  totalLiabilities?: number;
  totalEquity?: number;
  /** Cash and equivalents, including short-term investments where the source lumps them together. */
  cashAndEquivalents?: number;
  totalDebt?: number;
  /** Total debt minus cash. Negative for a company holding more cash than debt, which is
   *  meaningful rather than an error. */
  netDebt?: number;

  /** Return on equity, as a percentage. */
  returnOnEquity?: number;
  /** Return on invested capital, as a percentage. The single most useful number in a discussion of
   *  competitive advantage: a business that earns well above its cost of capital, year after year,
   *  is being protected by something. */
  returnOnInvestedCapital?: number;
  /** Return on assets, as a percentage. */
  returnOnAssets?: number;

  /** Diluted share count, for per-share work and for seeing dilution over time. */
  sharesOutstanding?: number;
  /** Dividend per share for the period. */
  dividendPerShare?: number;
  /** Dividends paid ÷ net income, as a percentage. */
  payoutRatio?: number;
  /** Market capitalisation at the report date. */
  marketCap?: number;
  /** Enterprise value: market cap plus net debt. */
  enterpriseValue?: number;
}
